(() => {
  const readJSON=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback));}catch{return fallback;}};
  const escapeHTML=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
  const safeAvatar=value=>typeof value==='string'&&/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(value)?value:'';
  const safeListingPhoto=value=>typeof value==='string'&&/^(data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+|assets\/listings\/[A-Za-z0-9._-]+)$/.test(value)?value:'';
  const currentUser=()=>{const user=readJSON('xox_user',null);if(!user)return null;const account=readJSON('xox_accounts',[]).find(item=>String(item.id)===String(user.id)||item.email===user.email);return account?{...user,name:user.name||account.name,email:user.email||account.email,phone:user.phone||account.phone||'',country:user.country||account.country||'',city:user.city||account.city||'',address:user.address||account.address||'',website:user.website||account.website||'',gender:user.gender||account.gender||'',age:user.age||account.age||'',bio:user.bio||account.bio||'',avatar:safeAvatar(user.avatar||account.avatar)}:{...user,avatar:safeAvatar(user.avatar)};};
  const emitChange=()=>window.dispatchEvent(new CustomEvent('xox:auth-change',{detail:currentUser()}));
  const hashPassword=async password=>{const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(password));return[...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,'0')).join('');};
  const fileToAvatar=file=>new Promise((resolve,reject)=>{if(!file)return resolve('');if(file.size>8*1024*1024)return reject(new Error('Аватар должен быть меньше 8 МБ.'));const reader=new FileReader();reader.onerror=()=>reject(new Error('Не удалось прочитать изображение.'));reader.onload=()=>{const image=new Image();image.onerror=()=>reject(new Error('Не удалось обработать изображение.'));image.onload=()=>{const size=256,canvas=document.createElement('canvas');canvas.width=size;canvas.height=size;const context=canvas.getContext('2d'),scale=Math.max(size/image.width,size/image.height),width=image.width*scale,height=image.height*scale;context.drawImage(image,(size-width)/2,(size-height)/2,width,height);resolve(canvas.toDataURL('image/jpeg',.78));};image.src=reader.result;};reader.readAsDataURL(file);});
  const registerAccount=async({name,email,phone='',country='',city='',address='',website='',gender='',age='',bio='',avatar='',password})=>{const accounts=readJSON('xox_accounts',[]),normalized=email.trim().toLowerCase();if(accounts.some(account=>account.email===normalized))throw new Error('Аккаунт с таким email уже существует.');const account={id:Date.now(),name:name.trim(),email:normalized,phone:phone.trim(),country:country.trim(),city:city.trim(),address:address.trim(),website:website.trim(),gender,age:String(age||''),bio:bio.trim(),avatar:safeAvatar(avatar),passwordHash:await hashPassword(password)};accounts.push(account);localStorage.setItem('xox_accounts',JSON.stringify(accounts));const user={id:account.id,name:account.name,email:account.email,phone:account.phone,country:account.country,city:account.city,address:account.address,website:account.website,gender:account.gender,age:account.age,bio:account.bio,avatar:account.avatar};localStorage.setItem('xox_user',JSON.stringify(user));emitChange();return user;};

  document.body.insertAdjacentHTML('beforeend',`<dialog id="authModal" class="auth-modal">
    <button type="button" class="auth-close" data-auth-close aria-label="Закрыть">×</button>
    <div class="auth-mark">XOX</div><h2>Добро пожаловать</h2><p class="auth-lead">Войдите, чтобы добавлять вещи, сохранять обмены и общаться с участниками.</p>
    <div class="auth-tabs"><button type="button" class="active" data-auth-mode="login">Войти</button><button type="button" data-auth-mode="register">Регистрация</button></div>
    <form id="authLogin" class="auth-form"><label>Email<input name="email" type="email" autocomplete="email" required placeholder="you@example.com"></label><label>Пароль<input name="password" type="password" autocomplete="current-password" required></label><div class="auth-captcha"><div><small>Проверка, что вы человек</small><b data-captcha-question></b></div><button type="button" data-captcha-refresh aria-label="Обновить CAPTCHA">↻</button></div><label>Ответ CAPTCHA<input name="captcha" inputmode="numeric" required autocomplete="off"></label><div class="auth-message" role="status"></div><button type="submit" class="auth-submit">Войти →</button></form>
    <form id="authRegister" class="auth-form" hidden><label>Имя*<input name="name" required autocomplete="name"></label><div class="auth-grid"><label>Страна*<select name="country" required autocomplete="country-name"><option value="">Выберите</option><option>Россия</option><option>Беларусь</option><option>Казахстан</option></select></label><label>Город*<input name="city" required autocomplete="address-level2"></label></div><label>Email*<input name="email" type="email" required autocomplete="email"></label><label>Телефон<input name="phone" type="tel" autocomplete="tel"></label><label>Адрес для карты<input name="address" autocomplete="street-address" placeholder="Необязательно"></label><label class="auth-avatar-upload">Аватар<input name="avatar" type="file" accept="image/jpeg,image/png,image/webp"><span>＋ Загрузить фотографию</span></label><div class="auth-grid"><label>Пароль*<input name="password" type="password" minlength="6" required autocomplete="new-password"></label><label>Повторите пароль*<input name="confirm" type="password" minlength="6" required autocomplete="new-password"></label></div><div class="auth-captcha"><div><small>Проверка, что вы человек</small><b data-captcha-question></b></div><button type="button" data-captcha-refresh aria-label="Обновить CAPTCHA">↻</button></div><label>Ответ CAPTCHA<input name="captcha" inputmode="numeric" required autocomplete="off"></label><div class="auth-message" role="status"></div><button type="submit" class="auth-submit">Создать аккаунт →</button></form>
    <div id="authProfile" class="auth-profile" hidden><div class="auth-profile-head"><div class="auth-avatar" data-auth-avatar><img data-auth-avatar-image alt="Аватар"><span data-auth-avatar-letter>Х</span></div><div><small>Личный кабинет</small><h3 data-auth-name></h3><p data-auth-email></p></div></div><div class="auth-profile-actions"><a href="add-listing.html">＋ Добавить</a><button type="button" data-profile-edit>Редактировать данные</button><button type="button" data-auth-logout>Выйти</button></div><form id="authProfileEdit" class="auth-profile-edit" hidden><div class="auth-grid"><label>Имя*<input name="name" required></label><label>Email*<input name="email" type="email" required></label><label>Страна<input name="country"></label><label>Город<input name="city"></label><label>Телефон<input name="phone" type="tel"></label><label>Адрес для карты<input name="address"></label><label>Сайт<input name="website" type="url" placeholder="https://"></label><label>Пол<select name="gender"><option value="">Не указывать</option><option>Мужской</option><option>Женский</option></select></label><label>Возраст<input name="age" type="number" min="14" max="120"></label></div><label>О себе<textarea name="bio" rows="3"></textarea></label><label class="auth-avatar-upload">Новый аватар<input name="avatar" type="file" accept="image/jpeg,image/png,image/webp"><span>Выбрать фотографию</span></label><div class="auth-message" role="status"></div><div class="auth-edit-actions"><button type="button" data-profile-cancel>Отмена</button><button type="submit">Сохранить →</button></div></form><section class="auth-my-listings"><div class="auth-listing-tabs"><button class="active" type="button" data-profile-list="own">Мои объявления</button><button type="button" data-profile-list="favorites">Избранное <span data-profile-favorites-count>0</span></button></div><div data-auth-listings></div></section></div>
  </dialog>`);

  const modal=document.querySelector('#authModal'),loginForm=document.querySelector('#authLogin'),registerForm=document.querySelector('#authRegister'),profile=document.querySelector('#authProfile'),profileEdit=document.querySelector('#authProfileEdit');
  const captcha=form=>{const a=Math.floor(Math.random()*8)+2,b=Math.floor(Math.random()*8)+2;form.dataset.captcha=String(a+b);form.querySelector('[data-captcha-question]').textContent=`${a} + ${b} = ?`;form.elements.captcha.value='';};
  const updateButtons=()=>{const user=currentUser();document.querySelectorAll('.login,#authStatus').forEach(button=>button.textContent=user?`● ${user.name}`:'Войти');};
  const ownedListings=user=>readJSON('xox_listings',[]).filter(item=>String(item.owner?.id||'')===String(user.id)||item.owner?.email===user.email||item.owner?.name===user.name).sort((a,b)=>(Date.parse(b.updatedAt||b.createdAt)||Number(b.id)||0)-(Date.parse(a.updatedAt||a.createdAt)||Number(a.id)||0));
  const profileFavoriteEntries=user=>{const store=readJSON('xox_favorites',{}),entries=store[String(user.id||user.email)];return Array.isArray(entries)?entries:[];};
  const profileListingRow=(item,mode)=>{const service=item.kind==='service'||item.kind==='Услуги',type=service?'Услуга':'Вещь',operations=Array.isArray(item.operations)&&item.operations.length?item.operations.join(' · '):(item.type||'Активно'),photos=Array.isArray(item.images)?item.images:[item.image],photo=photos.map(safeListingPhoto).find(Boolean)||(/фото|камер|instax|fujifilm/i.test(`${item.title||''} ${item.category||''}`)?'assets/listings/fujifilm-instax-mini-12-pink.webp':'assets/listings/listing-placeholder.svg'),price=item.price?(item.currency?`${Number(item.price).toLocaleString('ru-RU')} ${escapeHTML(item.currency)}`:escapeHTML(item.price)):(String(operations).includes('Даром')?'Бесплатно':'');return `<article class="auth-listing-row"><a class="auth-listing-main" href="product.html?id=${encodeURIComponent(item.id)}"><img src="${photo}" alt="${escapeHTML(item.title||'Предложение')}"><span><small>${type} · ${escapeHTML(operations)}</small><b>${escapeHTML(item.title||'Новое предложение')}</b>${price?`<strong>${price}</strong>`:''}</span></a>${mode==='own'?`<a class="auth-listing-edit" href="edit-listing.html?id=${encodeURIComponent(item.id)}" aria-label="Редактировать ${escapeHTML(item.title||'предложение')}" title="Редактировать">✎</a>`:`<button class="auth-favorite-remove" type="button" data-profile-favorite-remove="${escapeHTML(item.id)}" aria-label="Убрать из избранного" title="Убрать из избранного">♥</button>`}</article>`;};
  let profileListMode='own';
  const renderProfile=()=>{const user=currentUser();if(!user)return;profile.querySelector('[data-auth-name]').textContent=user.name;profile.querySelector('[data-auth-email]').textContent=user.email;const image=profile.querySelector('[data-auth-avatar-image]'),letter=profile.querySelector('[data-auth-avatar-letter]');if(user.avatar){image.src=user.avatar;image.hidden=false;letter.hidden=true;}else{image.removeAttribute('src');image.hidden=true;letter.hidden=false;letter.textContent=user.name.charAt(0).toUpperCase();}const favorites=profileFavoriteEntries(user),catalog=Array.isArray(window.XOXCatalog)?window.XOXCatalog:[],items=profileListMode==='own'?ownedListings(user):favorites.map(entry=>catalog.find(item=>String(item.id)===String(entry.id))||entry),target=profile.querySelector('[data-auth-listings]');profile.querySelector('[data-profile-favorites-count]').textContent=favorites.length;profile.querySelectorAll('[data-profile-list]').forEach(button=>button.classList.toggle('active',button.dataset.profileList===profileListMode));target.innerHTML=items.length?items.map(item=>profileListingRow(item,profileListMode)).join(''):`<div class="auth-listings-empty">${profileListMode==='own'?'Вы ещё ничего не добавили.':'В избранном пока ничего нет.'}</div>`;};
  const setMode=mode=>{const user=currentUser(),isProfile=mode==='profile'&&user;loginForm.hidden=isProfile||mode!=='login';registerForm.hidden=isProfile||mode!=='register';profile.hidden=!isProfile;modal.querySelector('.auth-tabs').hidden=Boolean(isProfile);modal.querySelectorAll('[data-auth-mode]').forEach(button=>button.classList.toggle('active',button.dataset.authMode===mode));profileEdit.hidden=true;if(isProfile){profileListMode='own';renderProfile();}else captcha(mode==='register'?registerForm:loginForm);};
  const openAuth=()=>{setMode(currentUser()?'profile':'login');modal.showModal();};
  document.querySelectorAll('.login,#authStatus').forEach(button=>button.addEventListener('click',openAuth));
  modal.querySelector('[data-auth-close]').addEventListener('click',()=>modal.close());modal.addEventListener('click',event=>{if(event.target===modal)modal.close();});modal.querySelectorAll('[data-auth-mode]').forEach(button=>button.addEventListener('click',()=>setMode(button.dataset.authMode)));modal.querySelectorAll('[data-captcha-refresh]').forEach(button=>button.addEventListener('click',()=>captcha(button.closest('form'))));
  loginForm.addEventListener('submit',async event=>{event.preventDefault();const message=loginForm.querySelector('.auth-message');message.textContent='';if(loginForm.elements.captcha.value.trim()!==loginForm.dataset.captcha){message.textContent='Неверный ответ CAPTCHA.';return captcha(loginForm);}const email=loginForm.elements.email.value.trim().toLowerCase(),account=readJSON('xox_accounts',[]).find(item=>item.email===email);if(!account||account.passwordHash!==await hashPassword(loginForm.elements.password.value)){message.textContent='Неверный email или пароль.';return captcha(loginForm);}localStorage.setItem('xox_user',JSON.stringify({id:account.id,name:account.name,email:account.email,phone:account.phone||'',country:account.country||'',city:account.city||'',address:account.address||'',avatar:safeAvatar(account.avatar)}));updateButtons();emitChange();modal.close();loginForm.reset();});
  registerForm.addEventListener('submit',async event=>{event.preventDefault();const message=registerForm.querySelector('.auth-message');message.textContent='';if(registerForm.elements.captcha.value.trim()!==registerForm.dataset.captcha){message.textContent='Неверный ответ CAPTCHA.';return captcha(registerForm);}if(registerForm.elements.password.value!==registerForm.elements.confirm.value){message.textContent='Пароли не совпадают.';return;}try{const avatar=await fileToAvatar(registerForm.elements.avatar.files[0]);await registerAccount({name:registerForm.elements.name.value,email:registerForm.elements.email.value,phone:registerForm.elements.phone.value,country:registerForm.elements.country.value,city:registerForm.elements.city.value,address:registerForm.elements.address.value,avatar,password:registerForm.elements.password.value});updateButtons();modal.close();registerForm.reset();}catch(error){message.textContent=error.message;captcha(registerForm);}});
  profile.querySelector('[data-profile-edit]').addEventListener('click',()=>{const user=currentUser();['name','email','country','city','phone','address','website','gender','age','bio'].forEach(name=>profileEdit.elements[name].value=user[name]||'');profileEdit.hidden=false;profileEdit.scrollIntoView({behavior:'smooth',block:'nearest'});});
  profile.querySelectorAll('[data-profile-list]').forEach(button=>button.addEventListener('click',()=>{profileListMode=button.dataset.profileList;renderProfile();}));
  profile.querySelector('[data-auth-listings]').addEventListener('click',event=>{const button=event.target.closest('[data-profile-favorite-remove]');if(!button)return;const user=currentUser(),store=readJSON('xox_favorites',{}),key=String(user.id||user.email),entries=Array.isArray(store[key])?store[key]:[];store[key]=entries.filter(item=>String(item.id)!==button.dataset.profileFavoriteRemove);localStorage.setItem('xox_favorites',JSON.stringify(store));renderProfile();window.dispatchEvent(new CustomEvent('xox:favorites-change'));});
  profile.querySelector('[data-profile-cancel]').addEventListener('click',()=>{profileEdit.hidden=true;profileEdit.reset();});
  profileEdit.addEventListener('submit',async event=>{event.preventDefault();const message=profileEdit.querySelector('.auth-message'),oldUser=currentUser(),accounts=readJSON('xox_accounts',[]),accountIndex=accounts.findIndex(item=>String(item.id)===String(oldUser.id)||item.email===oldUser.email),email=profileEdit.elements.email.value.trim().toLowerCase();message.textContent='';if(accounts.some((account,index)=>index!==accountIndex&&account.email===email)){message.textContent='Этот email уже используется.';return;}try{const selected=profileEdit.elements.avatar.files[0],avatar=selected?await fileToAvatar(selected):oldUser.avatar||'',updated={...accounts[accountIndex],id:oldUser.id,name:profileEdit.elements.name.value.trim(),email,phone:profileEdit.elements.phone.value.trim(),country:profileEdit.elements.country.value.trim(),city:profileEdit.elements.city.value.trim(),address:profileEdit.elements.address.value.trim(),website:profileEdit.elements.website.value.trim(),gender:profileEdit.elements.gender.value,age:profileEdit.elements.age.value,bio:profileEdit.elements.bio.value.trim(),avatar},publicUser={id:updated.id,name:updated.name,email:updated.email,phone:updated.phone,country:updated.country,city:updated.city,address:updated.address,website:updated.website,gender:updated.gender,age:updated.age,bio:updated.bio,avatar:updated.avatar};if(accountIndex>=0)accounts[accountIndex]=updated;else accounts.push(updated);localStorage.setItem('xox_accounts',JSON.stringify(accounts));localStorage.setItem('xox_user',JSON.stringify(publicUser));const listings=readJSON('xox_listings',[]).map(item=>{const owned=String(item.owner?.id||'')===String(oldUser.id)||item.owner?.email===oldUser.email||item.owner?.name===oldUser.name;if(!owned)return item;return{...item,sellerName:updated.name,phone:updated.phone,email:updated.email,owner:{...item.owner,id:updated.id,name:updated.name,email:updated.email,phone:updated.phone,country:updated.country,city:updated.city,address:updated.address,avatar:updated.avatar}};});localStorage.setItem('xox_listings',JSON.stringify(listings));profileEdit.hidden=true;profileEdit.reset();updateButtons();renderProfile();emitChange();}catch(error){message.textContent=error.message;}});
  modal.querySelector('[data-auth-logout]').addEventListener('click',()=>{localStorage.removeItem('xox_user');updateButtons();emitChange();modal.close();});
  updateButtons();window.XOXAuth={currentUser,registerAccount,fileToAvatar,open:openAuth};
})();
