const editRoot=document.querySelector('#editListingRoot');
const escapeEdit=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
const readEditListings=()=>{try{const data=JSON.parse(localStorage.getItem('xox_listings')||'[]');return Array.isArray(data)?data:[];}catch{return[];}};
const listingId=new URLSearchParams(location.search).get('id'),storedListings=readEditListings(),listingIndex=storedListings.findIndex(item=>String(item.id)===listingId),listing=storedListings[listingIndex],user=window.XOXAuth?.currentUser();
const isOwner=Boolean(user&&listing&&(String(listing.owner?.id||'')===String(user.id)||listing.owner?.email===user.email||listing.owner?.name===user.name));
const cameraLike=listing&&/фото|камер|instax|fujifilm/i.test(`${listing.title||''} ${listing.category||''}`),fallbackImage=cameraLike?'assets/listings/fujifilm-instax-mini-12-pink.webp':'assets/listings/listing-placeholder.svg',safeEditImage=value=>typeof value==='string'&&/^(data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+|assets\/listings\/[A-Za-z0-9._-]+)$/.test(value);
let editedPhotos=(Array.isArray(listing?.images)?listing.images:[listing?.image]).filter(safeEditImage).slice(0,6);
function optimizeEditPhoto(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{const image=new Image();image.onerror=reject;image.onload=()=>{const max=720,scale=Math.min(1,max/Math.max(image.width,image.height)),canvas=document.createElement('canvas');canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);const context=canvas.getContext('2d');context.fillStyle='#fff';context.fillRect(0,0,canvas.width,canvas.height);context.drawImage(image,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',.66));};image.src=reader.result;};reader.readAsDataURL(file);});}
if(!listing){editRoot.innerHTML='<div class="edit-empty"><h1>Объявление не найдено</h1><p>Возможно, оно было удалено или создано в другом браузере.</p><a href="catalog.html">Вернуться в каталог →</a></div>';}
else if(!isOwner){editRoot.innerHTML='<div class="edit-empty"><h1>Редактирование недоступно</h1><p>Изменять объявление может только его владелец после входа.</p><button id="editLogin">Войти</button></div>';document.querySelector('#editLogin').addEventListener('click',()=>window.XOXAuth.open());}
else{
  const operations=Array.isArray(listing.operations)?listing.operations:[],servicePlaces=Array.isArray(listing.servicePlace)?listing.servicePlace:[],isService=listing.kind==='service';
  editRoot.innerHTML=`<div class="edit-layout"><aside class="edit-aside"><div class="eyebrow"><i></i> ваше предложение</div><h1>Обновите<br><em>${escapeEdit(listing.title)}</em></h1><p>Изменения появятся в каталоге и карточке сразу после сохранения.</p></aside><section class="edit-card"><form id="editListingForm"><div class="edit-photo"><div id="editPhotoGallery" class="edit-photo-gallery"></div><div><label class="edit-upload">Добавить фотографии<input id="editPhotoInput" type="file" accept="image/*" multiple></label><button type="button" id="removeEditPhoto">Удалить все фото</button><small>До 6 файлов, каждый до 10 МБ</small></div></div><div class="form-grid"><label class="wide">Название*<input name="title" required value="${escapeEdit(listing.title)}"></label><label>Цена<input name="price" type="number" min="0" value="${escapeEdit(listing.price)}"></label><label>Валюта<select name="currency"><option ${listing.currency==='RUB'?'selected':''}>RUB</option><option ${listing.currency==='USD'?'selected':''}>USD</option><option ${listing.currency==='EUR'?'selected':''}>EUR</option></select></label><label class="wide">Описание*<textarea name="description" rows="7" required>${escapeEdit(listing.description)}</textarea></label><label class="wide">Метки<input name="keywords" value="${escapeEdit(listing.keywords)}" placeholder="камера, фото, техника"><small>Укажите через запятую</small></label>${isService?`<div class="wide service-place-edit"><span class="field-title">Место оказания услуги*</span><div class="place-grid">${['Удалённо','С выездом','Без выезда'].map(value=>`<label><input type="checkbox" name="servicePlace" value="${value}" ${servicePlaces.includes(value)?'checked':''}><b>${value}</b></label>`).join('')}</div></div>`:`<label>Состояние<select name="condition">${['Отличное','Хорошее','Есть следы использования','Требует ремонта'].map(value=>`<option ${listing.condition===value?'selected':''}>${value}</option>`).join('')}</select></label>`}</div><div class="edit-operations"><span>Доступные операции</span>${['Обмен','Продажа','Аренда','Даром','Самовывоз'].map(value=>`<label><input type="checkbox" name="operations" value="${value}" ${operations.includes(value)?'checked':''}><b>${value}</b></label>`).join('')}</div><div id="editMessage" class="auth-message"></div><div class="edit-actions"><a href="product.html?id=${encodeURIComponent(listing.id)}">Отмена</a><button type="submit">Сохранить изменения →</button></div></form></section></div>`;
  const editForm=document.querySelector('#editListingForm'),gallery=document.querySelector('#editPhotoGallery'),message=document.querySelector('#editMessage');
  function renderEditPhotos(){gallery.innerHTML=editedPhotos.length?editedPhotos.map((src,index)=>`<figure><img src="${src}" alt="Фотография ${index+1}"><button type="button" data-remove-photo="${index}" aria-label="Удалить фотографию ${index+1}">×</button></figure>`).join(''):`<img class="edit-photo-empty" src="${fallbackImage}" alt="Фотография не загружена">`;gallery.querySelectorAll('[data-remove-photo]').forEach(button=>button.addEventListener('click',()=>{editedPhotos.splice(Number(button.dataset.removePhoto),1);renderEditPhotos();}));}
  renderEditPhotos();
  document.querySelector('#editPhotoInput').addEventListener('change',async event=>{const files=[...event.target.files].slice(0,6-editedPhotos.length);if(!files.length)return;if(files.some(file=>file.size>10*1024*1024)){message.textContent='Каждая фотография должна быть меньше 10 МБ.';return;}try{for(const file of files)editedPhotos.push(await optimizeEditPhoto(file));renderEditPhotos();message.textContent=editedPhotos.length===6?'Добавлено максимальное количество фотографий.':'';}catch{message.textContent='Не удалось обработать одну из фотографий.';}event.target.value='';});
  document.querySelector('#removeEditPhoto').addEventListener('click',()=>{editedPhotos=[];renderEditPhotos();});
  editForm.addEventListener('submit',event=>{event.preventDefault();const data=new FormData(editForm),operations=data.getAll('operations'),places=data.getAll('servicePlace');if(!operations.length){message.textContent='Выберите хотя бы одну операцию.';return;}if(isService&&!places.length){message.textContent='Выберите хотя бы одно место оказания услуги.';return;}const updated={...listing,title:data.get('title').trim(),price:data.get('price'),currency:data.get('currency'),description:data.get('description').trim(),keywords:data.get('keywords').trim(),condition:isService?'':data.get('condition'),servicePlace:places,operations,updatedAt:new Date().toISOString()};if(editedPhotos.length){updated.images=[...editedPhotos];updated.image=editedPhotos[0];}else{delete updated.images;delete updated.image;}storedListings[listingIndex]=updated;try{localStorage.setItem('xox_listings',JSON.stringify(storedListings));location.href=`product.html?id=${encodeURIComponent(updated.id)}&updated=1`;}catch{message.textContent='Не удалось сохранить: фотографии слишком большие для браузера.';}});
}
